

# --- !Ups

create table "AVAILABILITIES" ("NAME" VARCHAR(254) NOT NULL,"DATE" VARCHAR(254) NOT NULL,"PARKID" INTEGER NOT NULL,"ID" SERIAL NOT NULL PRIMARY KEY);
create table "SITES" ("NAME" VARCHAR(254) NOT NULL,"ID" SERIAL NOT NULL PRIMARY KEY,"PARKID" INTEGER NOT NULL);
create table "SUBSCRIPTIONS" ("PHONE" VARCHAR(254) NOT NULL,"DATE" VARCHAR(254) NOT NULL,"PARKID" INTEGER NOT NULL,"ID" SERIAL NOT NULL PRIMARY KEY);

# --- !Downs

# drop table "SUBSCRIPTIONS";
# drop table "SITES";
# drop table "AVAILABILITIES";

